# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/sinem/Desktop/yeni/deneme.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AnaPencere(object):
    def setupUi(self, AnaPencere):
        AnaPencere.setObjectName("AnaPencere")
        AnaPencere.resize(600, 600)
        AnaPencere.setMinimumSize(QtCore.QSize(600, 600))
        AnaPencere.setMaximumSize(QtCore.QSize(600, 600))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        AnaPencere.setFont(font)
        self.label = QtWidgets.QLabel(AnaPencere)
        self.label.setGeometry(QtCore.QRect(50, 190, 571, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(AnaPencere)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 70, 421, 93))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(7)
        self.formLayout.setObjectName("formLayout")
        self.pingButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pingButton.setObjectName("pingButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pingButton)
        self.pingkutu = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pingkutu.setObjectName("pingkutu")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pingkutu)
        self.ipButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.ipButton.setObjectName("ipButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ipButton)
        self.ipkutu = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ipkutu.setObjectName("ipkutu")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ipkutu)
        self.gridLayoutWidget = QtWidgets.QWidget(AnaPencere)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 240, 431, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox.setMinimumSize(QtCore.QSize(45, 27))
        self.spinBox.setMaximum(65565)
        self.spinBox.setSingleStep(0)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 1, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.portButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.portButton.setObjectName("portButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.portButton)
        self.portkutu = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.portkutu.setObjectName("portkutu")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.portkutu)
        self.gridLayout.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(AnaPencere)
        self.cancelButton.setGeometry(QtCore.QRect(250, 560, 93, 28))
        self.cancelButton.setObjectName("cancelButton")
        self.label_2 = QtWidgets.QLabel(AnaPencere)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 881, 31))
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AnaPencere)
        self.label_3.setGeometry(QtCore.QRect(80, 320, 451, 16))
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(AnaPencere)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 370, 511, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.port_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.port_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.port_label.setText("")
        self.port_label.setTextFormat(QtCore.Qt.AutoText)
        self.port_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.port_label.setObjectName("port_label")
        self.verticalLayout.addWidget(self.port_label)

        self.retranslateUi(AnaPencere)
        QtCore.QMetaObject.connectSlotsByName(AnaPencere)

    def retranslateUi(self, AnaPencere):
        _translate = QtCore.QCoreApplication.translate
        AnaPencere.setWindowTitle(_translate("AnaPencere", "Form"))
        self.label.setText(_translate("AnaPencere", "Sitenin portunu test etmek istiyorsanz ip adresi -->port eklinde yazz."))
        self.pingButton.setText(_translate("AnaPencere", "PING"))
        self.ipButton.setText(_translate("AnaPencere", "IP"))
        self.portButton.setText(_translate("AnaPencere", "PORT TARA"))
        self.cancelButton.setText(_translate("AnaPencere", "OK"))
        self.label_3.setText(_translate("AnaPencere", "Port Tarama Son:(Local portlarn taramas daha hzldr.)"))

